# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: postgres:9.4.19
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: track-it_test
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run Tests
          command: bundle exec rspec spec

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
