# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1


orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch-node
    steps:
      - checkout
      - ruby/bundle-install
      - run:
          name: Run Tests
          command: bundle exec rspec spec

# What to do next? Set up a test job. Please see
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
